Feature/13/Tag Submit Logic 구현
Team-TravelGenie/TravelGenie_V1 pull request #29
Opened 2023-08-23 23:10 UTC by iOS-Woong

**TagCell Submit 로직 관련**

- 순서: TagCollectionViewCell -> TagContentCell -> ChatInterfaceViewController -> ChatViewController
- 순서에 맞도록 [선택 -> 제출 -> 수신 -> 오버라이드] 가능하도록 구현해두었습니다. 
- ChatViewController에서 제출한 태그를 활용하여 ChatGPT에 요청하는 작업을 진행하면 될 것 같습니다

**MockTag 객체 관련**
- 현재, Domain Entity 작업이 많다고 하셔서 Tag 프로퍼티의 일부 속성을 수정하여야 할 일을 MockTag, MockTagItem으로 구현해두었습니다.
- 이 사항은 섬캣의 Entity 작업이 끝나고 제 PR도 머지된 다음 새로 커밋을 쳐서 올리겠습니다. 
(MockTag가 적용된 영역은 Presentation-View-Chat 부분입니다~)

2023-08-24 06:00 UTC, dev-summer requested changes
멋지네요 고생 많으셨습니다! 리뷰드릴 사항은 다음과 같습니다.

1. 현재 `CustomTagCollectionCell`에서 태그 컬렉션뷰의 행동을 대다수 처리하고 있는데, `CustomTagCollectionCell`의 셀 뷰모델을 만들어서 일부 로직을 뷰모델로 분리하면 어떨까요?
2. 전반적으로 배열 네이밍 시 `list`라는 표현을 사용하시는데 (예: `Tag`들을 담은 배열은 `tagList`), 애플에서는 보통 `tags`와 같이 명사 복수형을 사용해서 배열을 네이밍하는 경우가 많은 것 같아요. 그렇게 컨벤션을 맞추는 건 어떨까요? ([예시링크](https://developer.apple.com/documentation/uikit/uiview/1622614-subviews))

2023-08-25 03:46 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/TagView/TagCollectionViewCell.swift
> +            notifyTagSelection(sender: self.tagButton)
수정완료하였습니다!

2023-08-25 03:48 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/CustomTagContentCell.swift
> +                  let selectedList = tagStorage.getSelectedList() else {
수정 완료하였습니다

2023-08-25 04:55 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/TagView/TagCollectionViewCell.swift
> +        let deselectedState = UIButton.State(rawValue: 1)
```swift
let selectedState: UIButton.State = [.highlighted, .selected]
let deselectedState: UIButton.State = .highlighted
```
로 변수화하여 명시해두었습니다!

2023-08-25 04:57 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/MockTag.swift
> +    var isOn: Bool = false
아하 넵 알겠습니다!
MockTag는 사용하지않으니 그냥 두고,
해당 타입이 사용되는 파라미터명을 코어데이터 모델명에 맞춘 변수의 이름에
맞도록 수정하였습니다!

2023-08-25 05:09 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/TagStorage.swift
> +    func getSelectedList() -> [MockTag]? {
말씀하신게
유사한 기능을하는 func insertTags()
와도 더 맞는 네이밍 인 것 같네요
수정 완료했습니당!

2023-08-25 06:43 UTC, iOS-Woong commented
> 1.현재 CustomTagCollectionCell에서 태그 컬렉션뷰의 행동을 대다수 처리하고 있는데, CustomTagCollectionCell의 셀 뷰모델을 만들어서 일부 로직을 뷰모델로 분리하면 어떨까요?

1.
- 제 생각에도 불필요로직이 많아보여 해당 부분을 ViewModel로 분리하여 커밋올려뒀습니다!

> 2. 전반적으로 배열 네이밍 시 list라는 표현을 사용하시는데 (예: Tag들을 담은 배열은 tagList), 애플에서는 보통 tags와 같이 명사 복수형을 사용해서 배열을 네이밍하는 경우가 많은 것 같아요. 그렇게 컨벤션을 맞추는 건 어떨까요? 

2. 
- 예시링크가 오류가 있어서 해당 내용을 읽어보진 못했습니다. ㅠㅠ 디스코드로 다시 한번 더 링크 주신다면 네이밍하는데 참고하겠습니다!!
- 섬캣 말씀대로 배열 네이밍 시 List를 많이 사용한 것이 맞는 것 같습니다.
- 찾아보니,TagStorage or MessageStorage 내부의 TagList or MessageList에서 많이 사용했던 것 같습니당
- 저는 이 Storage를 만들었을 때, 배열명을 messages, tags 라고 지었던 것 같습니다.
- 하지만, 쓰다보니 TagStorage와 관련이 없는 외부의 함수 or 파라미터 or 변수들도 [tags, messages] 라는 네이밍을 많이 사용하더라구요
- 그래서 조금이라도 구분을 두는게 낫지않을까? 하는 생각에 tagList, messageList로 네이밍을 했던 것 같습니당
- 혹시 이를 확실하게 구분지을 수 있을만한 네이밍을 추천해주시면 해당 네이밍으로 수정해보겠습니다!

2023-08-25 07:03 UTC, dev-summer requested changes
> 하지만, 쓰다보니 TagStorage와 관련이 없는 외부의 함수 or 파라미터 or 변수들도 [tags, messages] 라는 네이밍을 많이 사용하더라구요

다른 곳에서 사용하고 있는 네이밍이라고 해서 적절한 네이밍인데도 불구하고 사용하지 않는 것은 저는 조금 동의하기 어려운 것 같습니다!
호출해서 사용할 때에는 앞에 `tagStorage.tags`와 같은 형태로 호출해서 사용하기 때문에, 오히려 이름이 같은 쪽이 가독성이 좋지 않을까요?
예: `tags = tagStorage.tags`

2023-08-25 07:03 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/CustomTagContentCellViewModel.swift
> +    func updateTagIsSelected(value: String, isSelected: Bool) {
요거 이름이 부자연스러운 것 같습니다.
`updateTagSelectionState`. `updateTagState` 등등 다른 표현으로 수정해주면 좋을 것 같습니다.

2023-08-25 07:15 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/CustomTagContentCell.swift
> +    func submitSelectedTags(_ isSelectedTags: [MockTag])
수정 완료되었습니다~

2023-08-25 07:16 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/TagView/TagCollectionViewCell.swift
> +        self.tagButton.layer.borderColor = UIColor.blueGrayLine.cgColor
수정완료되었슴당

2023-08-25 07:18 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/Cell/CustomTagCell/TagStorage.swift
> +        self.tagList = setDefaultTagList()
수정완료되었습니다~

2023-08-25 07:20 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/CustomTagContentCellViewModel.swift
> +    func updateTagIsSelected(value: String, isSelected: Bool) {
수정 완료되었습니다!

2023-08-25 07:32 UTC, dev-summer approved these changes
고생하셨습니다~~

2023-08-25 07:50 UTC, merged