Feature/24/사진업로드→GoogleVision요청→TagCell 기능구현
Team-TravelGenie/TravelGenie_V1 pull request #50
Opened 2023-08-30 16:32 UTC by iOS-Woong

**PHPickerView관련**
- 1장 추가하는 로직의 PHPickerView의 로직을 3장까지 선택가능하도록 변경
- 동작방식의 변경(일괄업로드 → 순차업로드로 변경)

**TagCell Self-Sizing 관련**
- MessageStorage에 존재하는 태그셀의 위치를 감지하여 태그셀의 Self-Sizing을 수행하도록 로직을 변경

**Upload Button의 활성화 여부 관련**
- ButtonStateDelegate를 통해서 하위 ViewModel에서 Button의 State를 관리하도록 구현
- Button의 State에 따라 버튼의 Attribute가 변환되도록 구현

**GoogleVision 관련** 
- UseCase 및 Repository Interface의 구현
- 응답을 받고, 후가공 이후 메시지 생성하도록 구현

**VisionResultsProcessor 관련**
- 두개의 요청(Label Detection / LandmarkDetection) 을 통해 받아온 응답의 우선순위 로직을 처리함.
- 우선순위에 따라서 태그를 생성하여 [Tag]를 반환

++
현재, 이 PR에는 번역에 대한 내용은 들어가있지않습니다!
근데 받아온 LabelDetection을 통해서 가져온 키워드가 
우려했던대로 너무... 1차원적입니다 (돌, 하늘, 빌딩, 새 등등)

이거 가능하다면 Fine-tune을 통해서 
해당 키워드를 여행에 관련된 키워드로 가공했으면 좋겠는데

의논해보고,
우란님과 1차원적인 라벨디텍션 결과를 가공가능여부에 대한 회의를 거치면 좋을 것 같습니당..

2023-08-30 17:21 UTC, dev-summer requested changes
Domain에 속하는 UseCase에서 현재 `Cancellable`을 반환하기 위해서 `import Moya`하고 있는데요,
이럴 경우에 UseCase가 특정 네트워크 모델에 종속되게 되는 건 아닐까요?
저는 그 부분이 조금 고민이 되어서 `Cancellable`을 반환하지 않도록 작성해보았는데 웅 생각은 어떤지 궁금합니다!

2023-08-30 17:21 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +    private (set) var uploadButtonState: Bool = true {
`키워드 보내기` 버튼 비활성화는 별도 브랜치에서 처리 예정이신가요?
`이미지 업로드`와 `키워드 보내기` 채팅하기 화면에서 한 번씩만 올릴 수 있도록 해야 하는건가 싶어서요!
아니면 요건 기획이랑 논의가 필요한 지점일 수도 있겠네용

2023-08-30 17:21 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/VisionResultProcessor.swift
> +    fileprivate struct VisionResults {
해당 파일 내의 다른 타입에서 이 객체를 사용할 게 아니라면, 굳이 `fileprivate`으로 두는 것 보다 `private`으로 처리해도 될 것 같습니다.

2023-08-30 17:21 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatViewModel.swift
> +        return nil
early exit이면 `guard`로 처리하면 더 깔끔할 것 같습니다!

2023-08-30 17:21 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatViewModel.swift
> +        }
`images.forEach` 안에서 원하는 동작을 다 처리해 준 후,
`forEach`문 밖에서 `updateUploadButtonState`와 `extractKeywordsFromImages`를 실행하면 어떨까요??

2023-08-30 17:27 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +    private (set) var uploadButtonState: Bool = true {
아! 그러네요 

현재, `이미지 업로드` 버튼은 사진을 올리면 비활성화되도록 구현해뒀는데요
`키워드 보내기`는 아직 비활성화 되도록 구현해두진 않았습니당

이거 ChatViewController 뿐 아니라, HistoryViewController에서도 필요하겠네요

이것도 `이미지 업로드`를 비활성화시키는 방법과 동일하게 viewModel에서 조절가능하도록 구현해두겠습니다!

2023-08-30 17:31 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/VisionResultProcessor.swift
> +    fileprivate struct VisionResults {
수정 완료하였습니다~

2023-08-30 17:34 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatViewModel.swift
> +        }
```swift
    func handlePhotoUploads(images: [UIImage]) {
        let totalPhotosToUpload = images.count
        var photoUploadCount = 0
        
        images.forEach {
            let photoMessage = makePhotoMessage(from: $0)
            
            photoUploadCount += 1
            insertMessage(photoMessage)
        }

        if totalPhotosToUpload == photoUploadCount {
            updateUploadButtonState(false)
            extractKeywordsFromImages(images: images)
        }
    }
```
그러네요 밖으로 꺼내주는게 더 낫겠네요 ~ 수정 완료하였습니다

2023-08-31 15:25 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +    private (set) var uploadButtonState: Bool = true {
키워드보내기 상태를 변경했을 때, 
상태변수와 버튼을 바인딩처리하여
제출을 성공적으로 마치면 비활성화 되도록 처리해두었습니다!

2023-08-31 16:11 UTC, merged